### PR TITLE
add {% json %} template tag

### PR DESCRIPTION
**Pull request by graingert**
`context = { "ham": "ham", "spam": "spam", "eggs": "eggs" }`

`{% json ham=ham eggs=eggs spam=spam %}` becomes: ` { "ham": "ham", "spam": "spam", "eggs": "eggs" }`

`{% json ham eggs spam %}` becomes: `["ham", "eggs", "spam"]`

### CODE REVIEW

**Comment by graingert** [comment]
@gavinwahl urgh rubbish, this only passes on ordered dict pythons

**Comment by graingert** [comment]
I'm also looking to create beginjson and endjson:

`context = { "ham": "ham", "spam": "spam", "eggs": "eggs" }`

```
{% beginjson %}
    ham=ham
    eggs=eggs
    spam=spam
{% endjson %}
```
becomes: ` { "ham": "ham", "spam": "spam", "eggs": "eggs" }`

```
{% beginjson %}
    ham
    eggs
    spam
{% endjson %}
 ```
becomes: `["ham", "eggs", "spam"]`

**Comment by gavinwahl** [comment]
I don't like this, it seems like too much to do in a template.

**Comment by graingert** [comment]
I'm currently trying to remove generated inline JS from a lot of templates
that are shared between multiple views. This template tag in practise is
very useful, especially for data-data attributes

**Comment by gavinwahl** [comment]
Project has been deprecated

**Pull request closed without merging**
