### PR TITLE
travis improvements

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by graingert** [comment]
@gavinwahl it turns out the tests wern't actually testing anything. the output of pytest was ignored by `python setup.py test` which swallowed the return code and always replaced it with 0

**Comment by graingert** [comment]
@gavinwahl can you take a look at this, please?

**Comment by graingert** [comment]
@gavinwahl can you take a look at this, please?

**Comment by gavinwahl** [comment]
Can you squash this?

**Comment by graingert** [comment]
I'd rather not because it would make keeping https://github.com/graingert/django-json-tag up to date harder

**Comment by graingert** [comment]
@gavinwahl I've merged master though. You can squash merge if you like

**Comment by graingert** [comment]
@gavinwahl github should give you the option to 'squash merge' this PR

**Comment by graingert** [comment]
squash merge

**Comment by gavinwahl** [comment]
Project has been deprecated

**Pull request closed without merging**
